name: Trigger auto deployment for data-modeling

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/data-modeling-AutoDeployTrigger-e4ae1be9-a810-453b-9214-3bc810119022.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DATAMODELING_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DATAMODELING_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DATAMODELING_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 4thcr.azurecr.io
          registryUsername: ${{ secrets.DATAMODELING_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DATAMODELING_REGISTRY_PASSWORD }}
          containerAppName: data-modeling
          resourceGroup: QuestSW
          imageToBuild: 4thcr.azurecr.io/data-modeling:${{ github.sha }}
          environmentVariables: |
            OPENAI_API_KEY=${{ secrets.OPEN_AI_KEY }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_



