name: Trivy Security Scan

permissions:
  id-token: write
  contents: read

on:
  workflow_run:
    workflows: ["Trigger auto deployment for data-modeling"]
    types:
      - completed
  workflow_dispatch:

jobs:
  trivy-scan:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DATAMODELING_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DATAMODELING_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DATAMODELING_AZURE_SUBSCRIPTION_ID }}

      - name: Docker login to ACR
        run: az acr login --name 4thcr

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 4thcr.azurecr.io/data-modeling:${{ github.event.workflow_run.head_sha }}
          format: json
          output: trivy-results.json
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH

      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy-results.json
